apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: billing-service
  description: Internal billing and usage aggregation service.
  tags:
    - billing
    - usage
spec:
  type: service
  lifecycle: experimental
  owner: group:platform-engineering
  system: developer-catalog
